[package]
name = "justbc"
version = "0.1.0"
authors = ["reslario <reslario.code@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.18.2"
tui = { version = "0.13.0", default-features = false, features = ["crossterm"] }
bc-tui = { path = "../../lib/bc-tui" }
gen-tui = { path = "../../lib/gen-tui", features = ["handle-input"] }
bandcamp-api = { path = "../../lib/bandcamp-api" }
stream = { path = "../../lib/stream" }
play = { path = "../../lib/play" }
event = { path = "../../lib/event" }
input = { path = "../../lib/input" }
fetch = { path = "../../lib/fetch" }
enumerate = "0.1.1"
bc-track = { path = "../../lib/bc-track" }
mp3 = { path = "../../lib/mp3" }
media-keys = { path = "../../lib/media-keys" }
serde = { version = "1.0.118", features = ["derive"] }
directories = "3.0.1"
structopt = "0.3.21"
structopt-toml = "0.4.5"
toml = "0.5.8"
